{
  "AccountStatus": 0,
  "ValidationFailed": false,
  "ValidationReport": null,
  "Website": 0,
  "Metadata": {
    "ObjectType": "Koopwoningen",
    "Omschrijving": "Koopwoningen > Amsterdam",
    "Titel": "Huizen te koop in Amsterdam"
  },
  "Objects": [
    {
      "AangebodenSindsTekst": "16 mei 2014",
      "AanmeldDatum": "2010-01-01T00:00:00+01:00",
      "AantalKamers": 5,
      "AantalKavels": null,
      "Adres": "G.J. Scheurleerweg 144",
      "Afstand": 0,
      "BronCode": "NVM",
      "ChildrenObjects": [],
      "DatumOndertekeningAkte": null,
      "Foto": "http://cloud.funda.nl/valentina_media/044/626/671_klein.jpg",
      "FotoLarge": "http://cloud.funda.nl/valentina_media/044/626/671_groot.jpg",
      "FotoLargest": "http://cloud.funda.nl/valentina_media/044/626/671_grotere.jpg",
      "FotoMedium": "http://cloud.funda.nl/valentina_media/044/626/671_middel.jpg",
      "FotoSecure": "http://cloud.funda.nl/valentina_media/044/626/671_klein.jpg",
      "GewijzigdDatum": null,
      "GlobalId": 2668721,
      "GroupByObjectType": "44e2a572-f71d-4962-b085-0e51039c3f12",
      "Heeft360GradenFoto": false,
      "HeeftBrochure": true,
      "HeeftOverbruggingsgrarantie": false,
      "HeeftPlattegrond": false,
      "HeeftTophuis": true,
      "HeeftVeiling": false,
      "HeeftVideo": false,
      "HuurPrijsTot": null,
      "Huurprijs": null,
      "HuurprijsFormaat": null,
      "Id": "44e2a572-f71d-4962-b085-0e51039c3f12",
      "InUnitsVanaf": null,
      "IndProjectObjectType": false,
      "IndTransactieMakelaarTonen": "true",
      "IsSearchable": true,
      "IsVerhuurd": false,
      "IsVerkocht": false,
      "IsVerkochtOfVerhuurd": false,
      "Koopprijs": 375000,
      "KoopprijsFormaat": "<[KoopPrijs]> <{kosten koper|kort}>",
      "KoopprijsTot": 375000,
      "MakelaarId": 12285,
      "MakelaarNaam": "Makelaarsland",
      "MobileURL": "http://m.funda.nl/obj.aspx?goi=2668721",
      "Note": null,
      "OpenHuis": [],
      "Oppervlakte": 0,
      "Perceeloppervlakte": 123,
      "Postcode": "1022KL",
      "Prijs": {
        "GeenExtraKosten": null,
        "HuurAbbreviation": "",
        "Huurprijs": null,
        "HuurprijsOpAanvraag": "",
        "HuurprijsTot": null,
        "KoopAbbreviation": "k.k.",
        "Koopprijs": 375000,
        "KoopprijsOpAanvraag": "",
        "KoopprijsTot": 375000,
        "OriginelePrijs": null,
        "VeilingText": ""
      },
      "PrijsGeformatteerdHtml": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;375.000</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "PrijsGeformatteerdTextHuur": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;375.000</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "PrijsGeformatteerdTextKoop": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;375.000</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "Producten": [
        "Top",
        "Brochure"
      ],
      "ProjectNaam": null,
      "PromoLabel": {
        "HasPromotionLabel": false,
        "PromotionPhotos": [],
        "PromotionPhotosSecure": null,
        "PromotionType": 0,
        "RibbonColor": 0,
        "RibbonText": null,
        "Tagline": null
      },
      "PublicatieDatum": "2014-05-16T01:05:12+02:00",
      "PublicatieStatus": 0,
      "SavedDate": null,
      "Soort-aanbod": "woonhuis",
      "SoortAanbod": 10,
      "StartOplevering": null,
      "TimeAgoText": null,
      "TransactieAfmeldDatum": null,
      "TransactieMakelaarId": null,
      "TransactieMakelaarNaam": null,
      "TypeProject": 0,
      "URL": "http://www.funda.nl/koop/amsterdam/huis-48013184-gj-scheurleerweg-144/",
      "VerkoopStatus": "StatusBeschikbaar",
      "WGS84_X": 4.932445,
      "WGS84_Y": 52.40768,
      "WoonOppervlakteTot": 133,
      "Woonoppervlakte": 133,
      "Woonplaats": "Amsterdam",
      "ZoekType": [
        10
      ]
    },
    {
      "AangebodenSindsTekst": "2 maanden",
      "AanmeldDatum": "2010-01-01T00:00:00+01:00",
      "AantalKamers": 2,
      "AantalKavels": null,
      "Adres": "Conradstraat 138 D",
      "Afstand": 0,
      "BronCode": "NVM",
      "ChildrenObjects": [],
      "DatumOndertekeningAkte": null,
      "Foto": "http://cloud.funda.nl/valentina_media/042/441/039_klein.jpg",
      "FotoLarge": "http://cloud.funda.nl/valentina_media/042/441/039_groot.jpg",
      "FotoLargest": "http://cloud.funda.nl/valentina_media/042/441/039_grotere.jpg",
      "FotoMedium": "http://cloud.funda.nl/valentina_media/042/441/039_middel.jpg",
      "FotoSecure": "http://cloud.funda.nl/valentina_media/042/441/039_klein.jpg",
      "GewijzigdDatum": null,
      "GlobalId": 2586815,
      "GroupByObjectType": "f1d65e84-2f90-4832-a692-ad760a33ffee",
      "Heeft360GradenFoto": false,
      "HeeftBrochure": false,
      "HeeftOverbruggingsgrarantie": false,
      "HeeftPlattegrond": false,
      "HeeftTophuis": true,
      "HeeftVeiling": false,
      "HeeftVideo": false,
      "HuurPrijsTot": null,
      "Huurprijs": null,
      "HuurprijsFormaat": null,
      "Id": "f1d65e84-2f90-4832-a692-ad760a33ffee",
      "InUnitsVanaf": null,
      "IndProjectObjectType": false,
      "IndTransactieMakelaarTonen": "true",
      "IsSearchable": true,
      "IsVerhuurd": false,
      "IsVerkocht": false,
      "IsVerkochtOfVerhuurd": false,
      "Koopprijs": 179000,
      "KoopprijsFormaat": "<[KoopPrijs]> <{kosten koper|kort}>",
      "KoopprijsTot": 179000,
      "MakelaarId": 24755,
      "MakelaarNaam": "Amsterdam @ Home Makelaars",
      "MobileURL": "http://m.funda.nl/obj.aspx?goi=2586815",
      "Note": null,
      "OpenHuis": [],
      "Oppervlakte": 0,
      "Perceeloppervlakte": null,
      "Postcode": "1018NM",
      "Prijs": {
        "GeenExtraKosten": null,
        "HuurAbbreviation": "",
        "Huurprijs": null,
        "HuurprijsOpAanvraag": "",
        "HuurprijsTot": null,
        "KoopAbbreviation": "k.k.",
        "Koopprijs": 179000,
        "KoopprijsOpAanvraag": "",
        "KoopprijsTot": 179000,
        "OriginelePrijs": null,
        "VeilingText": ""
      },
      "PrijsGeformatteerdHtml": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;179.000</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "PrijsGeformatteerdTextHuur": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;179.000</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "PrijsGeformatteerdTextKoop": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;179.000</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "Producten": [
        "Top"
      ],
      "ProjectNaam": null,
      "PromoLabel": {
        "HasPromotionLabel": false,
        "PromotionPhotos": [],
        "PromotionPhotosSecure": null,
        "PromotionType": 0,
        "RibbonColor": 0,
        "RibbonText": null,
        "Tagline": null
      },
      "PublicatieDatum": "2014-02-25T01:05:12+01:00",
      "PublicatieStatus": 0,
      "SavedDate": null,
      "Soort-aanbod": "appartement",
      "SoortAanbod": 10,
      "StartOplevering": null,
      "TimeAgoText": null,
      "TransactieAfmeldDatum": null,
      "TransactieMakelaarId": null,
      "TransactieMakelaarNaam": null,
      "TypeProject": 0,
      "URL": "http://www.funda.nl/koop/amsterdam/appartement-48931278-conradstraat-138-d/",
      "VerkoopStatus": "StatusBeschikbaar",
      "WGS84_X": 4.930729,
      "WGS84_Y": 52.37127,
      "WoonOppervlakteTot": 36,
      "Woonoppervlakte": 36,
      "Woonplaats": "Amsterdam",
      "ZoekType": [
        10
      ]
    },
    {
      "AangebodenSindsTekst": "<span title=\"langer dan 6 maanden\">6+ maanden</span>",
      "AanmeldDatum": "2010-01-01T00:00:00+01:00",
      "AantalKamers": 3,
      "AantalKavels": null,
      "Adres": "Van Spilbergenstraat 65 II",
      "Afstand": 0,
      "BronCode": "NVM",
      "ChildrenObjects": [],
      "DatumOndertekeningAkte": null,
      "Foto": "http://cloud.funda.nl/valentina_media/036/683/592_klein.jpg",
      "FotoLarge": "http://cloud.funda.nl/valentina_media/036/683/592_groot.jpg",
      "FotoLargest": "http://cloud.funda.nl/valentina_media/036/683/592_grotere.jpg",
      "FotoMedium": "http://cloud.funda.nl/valentina_media/036/683/592_middel.jpg",
      "FotoSecure": "http://cloud.funda.nl/valentina_media/036/683/592_klein.jpg",
      "GewijzigdDatum": null,
      "GlobalId": 2358705,
      "GroupByObjectType": "e8d0807c-16ef-4594-a820-376fd39e341d",
      "Heeft360GradenFoto": false,
      "HeeftBrochure": true,
      "HeeftOverbruggingsgrarantie": false,
      "HeeftPlattegrond": false,
      "HeeftTophuis": true,
      "HeeftVeiling": false,
      "HeeftVideo": false,
      "HuurPrijsTot": null,
      "Huurprijs": null,
      "HuurprijsFormaat": null,
      "Id": "e8d0807c-16ef-4594-a820-376fd39e341d",
      "InUnitsVanaf": null,
      "IndProjectObjectType": false,
      "IndTransactieMakelaarTonen": "true",
      "IsSearchable": true,
      "IsVerhuurd": false,
      "IsVerkocht": false,
      "IsVerkochtOfVerhuurd": false,
      "Koopprijs": 169500,
      "KoopprijsFormaat": "<[KoopPrijs]> <{kosten koper|kort}>",
      "KoopprijsTot": 169500,
      "MakelaarId": 12285,
      "MakelaarNaam": "Makelaarsland",
      "MobileURL": "http://m.funda.nl/obj.aspx?goi=2358705",
      "Note": null,
      "OpenHuis": [],
      "Oppervlakte": 0,
      "Perceeloppervlakte": null,
      "Postcode": "1057PZ",
      "Prijs": {
        "GeenExtraKosten": null,
        "HuurAbbreviation": "",
        "Huurprijs": null,
        "HuurprijsOpAanvraag": "",
        "HuurprijsTot": null,
        "KoopAbbreviation": "k.k.",
        "Koopprijs": 169500,
        "KoopprijsOpAanvraag": "",
        "KoopprijsTot": 169500,
        "OriginelePrijs": 175000,
        "VeilingText": ""
      },
      "PrijsGeformatteerdHtml": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;169.500</span> <abbr class=\"price-ext\">k.k.</abbr><br/><del class=\"price-del\"><span class=\"price\">&euro;&nbsp;175.000</span> <abbr class=\"price-ext\">k.k.</abbr></del></span>",
      "PrijsGeformatteerdTextHuur": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;169.500</span> <abbr class=\"price-ext\">k.k.</abbr><br/><del class=\"price-del\"><span class=\"price\">&euro;&nbsp;175.000</span> <abbr class=\"price-ext\">k.k.</abbr></del></span>",
      "PrijsGeformatteerdTextKoop": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;169.500</span> <abbr class=\"price-ext\">k.k.</abbr><br/><del class=\"price-del\"><span class=\"price\">&euro;&nbsp;175.000</span> <abbr class=\"price-ext\">k.k.</abbr></del></span>",
      "Producten": [
        "Top",
        "Brochure"
      ],
      "ProjectNaam": null,
      "PromoLabel": {
        "HasPromotionLabel": false,
        "PromotionPhotos": [],
        "PromotionPhotosSecure": null,
        "PromotionType": 0,
        "RibbonColor": 0,
        "RibbonText": null,
        "Tagline": null
      },
      "PublicatieDatum": "2013-05-25T01:05:13+02:00",
      "PublicatieStatus": 0,
      "SavedDate": null,
      "Soort-aanbod": "appartement",
      "SoortAanbod": 10,
      "StartOplevering": null,
      "TimeAgoText": null,
      "TransactieAfmeldDatum": null,
      "TransactieMakelaarId": null,
      "TransactieMakelaarNaam": null,
      "TypeProject": 0,
      "URL": "http://www.funda.nl/koop/amsterdam/appartement-48703168-van-spilbergenstraat-65-ii/",
      "VerkoopStatus": "StatusBeschikbaar",
      "WGS84_X": 4.851716,
      "WGS84_Y": 52.36631,
      "WoonOppervlakteTot": 50,
      "Woonoppervlakte": 50,
      "Woonplaats": "Amsterdam",
      "ZoekType": [
        10
      ]
    },
    {
      "AangebodenSindsTekst": "<span title=\"langer dan 6 maanden\">6+ maanden</span>",
      "AanmeldDatum": "2010-01-01T00:00:00+01:00",
      "AantalKamers": 3,
      "AantalKavels": null,
      "Adres": "Van Effenstraat 3 III",
      "Afstand": 0,
      "BronCode": "NVM",
      "ChildrenObjects": [],
      "DatumOndertekeningAkte": null,
      "Foto": "http://cloud.funda.nl/valentina_media/038/609/950_klein.jpg",
      "FotoLarge": "http://cloud.funda.nl/valentina_media/038/609/950_groot.jpg",
      "FotoLargest": "http://cloud.funda.nl/valentina_media/038/609/950_grotere.jpg",
      "FotoMedium": "http://cloud.funda.nl/valentina_media/038/609/950_middel.jpg",
      "FotoSecure": "http://cloud.funda.nl/valentina_media/038/609/950_klein.jpg",
      "GewijzigdDatum": null,
      "GlobalId": 2430180,
      "GroupByObjectType": "2ebcde8e-4c77-4feb-9426-ac9751c215b5",
      "Heeft360GradenFoto": true,
      "HeeftBrochure": true,
      "HeeftOverbruggingsgrarantie": true,
      "HeeftPlattegrond": true,
      "HeeftTophuis": true,
      "HeeftVeiling": false,
      "HeeftVideo": false,
      "HuurPrijsTot": null,
      "Huurprijs": null,
      "HuurprijsFormaat": null,
      "Id": "2ebcde8e-4c77-4feb-9426-ac9751c215b5",
      "InUnitsVanaf": null,
      "IndProjectObjectType": false,
      "IndTransactieMakelaarTonen": "true",
      "IsSearchable": true,
      "IsVerhuurd": false,
      "IsVerkocht": false,
      "IsVerkochtOfVerhuurd": false,
      "Koopprijs": 329000,
      "KoopprijsFormaat": "<[KoopPrijs]> <{kosten koper|kort}>",
      "KoopprijsTot": 329000,
      "MakelaarId": 24079,
      "MakelaarNaam": "Van der Linden",
      "MobileURL": "http://m.funda.nl/obj.aspx?goi=2430180",
      "Note": null,
      "OpenHuis": [],
      "Oppervlakte": 0,
      "Perceeloppervlakte": null,
      "Postcode": "1053BT",
      "Prijs": {
        "GeenExtraKosten": null,
        "HuurAbbreviation": "",
        "Huurprijs": null,
        "HuurprijsOpAanvraag": "",
        "HuurprijsTot": null,
        "KoopAbbreviation": "k.k.",
        "Koopprijs": 329000,
        "KoopprijsOpAanvraag": "",
        "KoopprijsTot": 329000,
        "OriginelePrijs": null,
        "VeilingText": ""
      },
      "PrijsGeformatteerdHtml": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;329.000</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "PrijsGeformatteerdTextHuur": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;329.000</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "PrijsGeformatteerdTextKoop": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;329.000</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "Producten": [
        "Top",
        "Overbruggingsgarantie",
        "Plattegrond",
        "360-fotos",
        "Brochure",
        "Featured"
      ],
      "ProjectNaam": null,
      "PromoLabel": {
        "HasPromotionLabel": true,
        "PromotionPhotos": [],
        "PromotionPhotosSecure": null,
        "PromotionType": 2,
        "RibbonColor": 1,
        "RibbonText": "kinkerbuurt",
        "Tagline": "Woning kopen? Goed idee. Zeker nu!"
      },
      "PublicatieDatum": "2013-08-24T00:00:00+02:00",
      "PublicatieStatus": 0,
      "SavedDate": null,
      "Soort-aanbod": "appartement",
      "SoortAanbod": 10,
      "StartOplevering": null,
      "TimeAgoText": null,
      "TransactieAfmeldDatum": null,
      "TransactieMakelaarId": null,
      "TransactieMakelaarNaam": null,
      "TypeProject": 0,
      "URL": "http://www.funda.nl/koop/amsterdam/appartement-48885543-van-effenstraat-3-iii/",
      "VerkoopStatus": "StatusBeschikbaar",
      "WGS84_X": 4.862847,
      "WGS84_Y": 52.36612,
      "WoonOppervlakteTot": 96,
      "Woonoppervlakte": 96,
      "Woonplaats": "Amsterdam",
      "ZoekType": [
        10
      ]
    },
    {
      "AangebodenSindsTekst": "17 mei 2014",
      "AanmeldDatum": "2010-01-01T00:00:00+01:00",
      "AantalKamers": 7,
      "AantalKavels": null,
      "Adres": "Herentalsstraat 24",
      "Afstand": 0,
      "BronCode": "NVM",
      "ChildrenObjects": [],
      "DatumOndertekeningAkte": null,
      "Foto": "http://cloud.funda.nl/valentina_media/044/584/913_klein.jpg",
      "FotoLarge": "http://cloud.funda.nl/valentina_media/044/584/913_groot.jpg",
      "FotoLargest": "http://cloud.funda.nl/valentina_media/044/584/913_grotere.jpg",
      "FotoMedium": "http://cloud.funda.nl/valentina_media/044/584/913_middel.jpg",
      "FotoSecure": "http://cloud.funda.nl/valentina_media/044/584/913_klein.jpg",
      "GewijzigdDatum": null,
      "GlobalId": 2669431,
      "GroupByObjectType": "8c96e1c0-6e99-4a8e-ba4f-5e2d3c31fb5d",
      "Heeft360GradenFoto": true,
      "HeeftBrochure": false,
      "HeeftOverbruggingsgrarantie": false,
      "HeeftPlattegrond": true,
      "HeeftTophuis": true,
      "HeeftVeiling": false,
      "HeeftVideo": false,
      "HuurPrijsTot": null,
      "Huurprijs": null,
      "HuurprijsFormaat": null,
      "Id": "8c96e1c0-6e99-4a8e-ba4f-5e2d3c31fb5d",
      "InUnitsVanaf": null,
      "IndProjectObjectType": false,
      "IndTransactieMakelaarTonen": "true",
      "IsSearchable": true,
      "IsVerhuurd": false,
      "IsVerkocht": false,
      "IsVerkochtOfVerhuurd": false,
      "Koopprijs": 448800,
      "KoopprijsFormaat": "<[KoopPrijs]> <{kosten koper|kort}>",
      "KoopprijsTot": 448800,
      "MakelaarId": 24663,
      "MakelaarNaam": "Urban Makelaars - Sander Lokhoff",
      "MobileURL": "http://m.funda.nl/obj.aspx?goi=2669431",
      "Note": null,
      "OpenHuis": [],
      "Oppervlakte": 0,
      "Perceeloppervlakte": 155,
      "Postcode": "1066NK",
      "Prijs": {
        "GeenExtraKosten": null,
        "HuurAbbreviation": "",
        "Huurprijs": null,
        "HuurprijsOpAanvraag": "",
        "HuurprijsTot": null,
        "KoopAbbreviation": "k.k.",
        "Koopprijs": 448800,
        "KoopprijsOpAanvraag": "",
        "KoopprijsTot": 448800,
        "OriginelePrijs": null,
        "VeilingText": ""
      },
      "PrijsGeformatteerdHtml": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;448.800</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "PrijsGeformatteerdTextHuur": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;448.800</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "PrijsGeformatteerdTextKoop": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;448.800</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "Producten": [
        "Top",
        "Plattegrond",
        "360-fotos",
        "Featured"
      ],
      "ProjectNaam": null,
      "PromoLabel": {
        "HasPromotionLabel": true,
        "PromotionPhotos": [],
        "PromotionPhotosSecure": null,
        "PromotionType": 2,
        "RibbonColor": 0,
        "RibbonText": "Grote tuin",
        "Tagline": "Goede ingedeeld 7 kamer Herenhuis met enorme leefruimtes, 5 slaapkamers en 2 badkamers.GBO: 230 M2!"
      },
      "PublicatieDatum": "2014-05-17T01:05:12+02:00",
      "PublicatieStatus": 0,
      "SavedDate": null,
      "Soort-aanbod": "woonhuis",
      "SoortAanbod": 10,
      "StartOplevering": null,
      "TimeAgoText": null,
      "TransactieAfmeldDatum": null,
      "TransactieMakelaarId": null,
      "TransactieMakelaarNaam": null,
      "TypeProject": 0,
      "URL": "http://www.funda.nl/koop/amsterdam/huis-48014894-herentalsstraat-24/",
      "VerkoopStatus": "StatusBeschikbaar",
      "WGS84_X": 4.807697,
      "WGS84_Y": 52.34952,
      "WoonOppervlakteTot": 180,
      "Woonoppervlakte": 180,
      "Woonplaats": "Amsterdam",
      "ZoekType": [
        10
      ]
    },
    {
      "AangebodenSindsTekst": "5 maanden",
      "AanmeldDatum": "2010-01-01T00:00:00+01:00",
      "AantalKamers": 2,
      "AantalKavels": null,
      "Adres": "Wethouder Insingerstraat 14",
      "Afstand": 0,
      "BronCode": "NVM",
      "ChildrenObjects": [],
      "DatumOndertekeningAkte": null,
      "Foto": "http://cloud.funda.nl/valentina_media/041/059/411_klein.jpg",
      "FotoLarge": "http://cloud.funda.nl/valentina_media/041/059/411_groot.jpg",
      "FotoLargest": "http://cloud.funda.nl/valentina_media/041/059/411_grotere.jpg",
      "FotoMedium": "http://cloud.funda.nl/valentina_media/041/059/411_middel.jpg",
      "FotoSecure": "http://cloud.funda.nl/valentina_media/041/059/411_klein.jpg",
      "GewijzigdDatum": null,
      "GlobalId": 2524223,
      "GroupByObjectType": "fb1fc54b-d269-47db-a423-599a8301dd72",
      "Heeft360GradenFoto": false,
      "HeeftBrochure": true,
      "HeeftOverbruggingsgrarantie": true,
      "HeeftPlattegrond": true,
      "HeeftTophuis": true,
      "HeeftVeiling": false,
      "HeeftVideo": false,
      "HuurPrijsTot": null,
      "Huurprijs": null,
      "HuurprijsFormaat": null,
      "Id": "fb1fc54b-d269-47db-a423-599a8301dd72",
      "InUnitsVanaf": null,
      "IndProjectObjectType": false,
      "IndTransactieMakelaarTonen": "true",
      "IsSearchable": true,
      "IsVerhuurd": false,
      "IsVerkocht": false,
      "IsVerkochtOfVerhuurd": false,
      "Koopprijs": 115000,
      "KoopprijsFormaat": "<[KoopPrijs]> <{kosten koper|kort}>",
      "KoopprijsTot": 115000,
      "MakelaarId": 24079,
      "MakelaarNaam": "Van der Linden",
      "MobileURL": "http://m.funda.nl/obj.aspx?goi=2524223",
      "Note": null,
      "OpenHuis": [],
      "Oppervlakte": 0,
      "Perceeloppervlakte": null,
      "Postcode": "1107XA",
      "Prijs": {
        "GeenExtraKosten": null,
        "HuurAbbreviation": "",
        "Huurprijs": null,
        "HuurprijsOpAanvraag": "",
        "HuurprijsTot": null,
        "KoopAbbreviation": "k.k.",
        "Koopprijs": 115000,
        "KoopprijsOpAanvraag": "",
        "KoopprijsTot": 115000,
        "OriginelePrijs": null,
        "VeilingText": ""
      },
      "PrijsGeformatteerdHtml": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;115.000</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "PrijsGeformatteerdTextHuur": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;115.000</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "PrijsGeformatteerdTextKoop": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;115.000</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "Producten": [
        "Top",
        "Overbruggingsgarantie",
        "Plattegrond",
        "Brochure",
        "Featured"
      ],
      "ProjectNaam": null,
      "PromoLabel": {
        "HasPromotionLabel": true,
        "PromotionPhotos": [],
        "PromotionPhotosSecure": null,
        "PromotionType": 2,
        "RibbonColor": 1,
        "RibbonText": "betaalbaar",
        "Tagline": "Benedenwoning met zonnige tuin op het westen."
      },
      "PublicatieDatum": "2013-12-12T00:00:00+01:00",
      "PublicatieStatus": 0,
      "SavedDate": null,
      "Soort-aanbod": "appartement",
      "SoortAanbod": 10,
      "StartOplevering": null,
      "TimeAgoText": null,
      "TransactieAfmeldDatum": null,
      "TransactieMakelaarId": null,
      "TransactieMakelaarNaam": null,
      "TypeProject": 0,
      "URL": "http://www.funda.nl/koop/amsterdam/appartement-48979686-wethouder-insingerstraat-14/",
      "VerkoopStatus": "StatusBeschikbaar",
      "WGS84_X": 4.986245,
      "WGS84_Y": 52.29206,
      "WoonOppervlakteTot": 54,
      "Woonoppervlakte": 54,
      "Woonplaats": "Amsterdam",
      "ZoekType": [
        10
      ]
    },
    {
      "AangebodenSindsTekst": "<span title=\"langer dan 6 maanden\">6+ maanden</span>",
      "AanmeldDatum": "2010-01-01T00:00:00+01:00",
      "AantalKamers": 2,
      "AantalKavels": null,
      "Adres": "Madurastraat 8 D",
      "Afstand": 0,
      "BronCode": "NVM",
      "ChildrenObjects": [],
      "DatumOndertekeningAkte": null,
      "Foto": "http://cloud.funda.nl/valentina_media/030/194/738_klein.jpg",
      "FotoLarge": "http://cloud.funda.nl/valentina_media/030/194/738_groot.jpg",
      "FotoLargest": "http://cloud.funda.nl/valentina_media/030/194/738_grotere.jpg",
      "FotoMedium": "http://cloud.funda.nl/valentina_media/030/194/738_middel.jpg",
      "FotoSecure": "http://cloud.funda.nl/valentina_media/030/194/738_klein.jpg",
      "GewijzigdDatum": null,
      "GlobalId": 2066858,
      "GroupByObjectType": "cc8f3b8f-1239-407e-a5a0-0c60dcb0a222",
      "Heeft360GradenFoto": false,
      "HeeftBrochure": true,
      "HeeftOverbruggingsgrarantie": false,
      "HeeftPlattegrond": false,
      "HeeftTophuis": true,
      "HeeftVeiling": false,
      "HeeftVideo": false,
      "HuurPrijsTot": null,
      "Huurprijs": null,
      "HuurprijsFormaat": null,
      "Id": "cc8f3b8f-1239-407e-a5a0-0c60dcb0a222",
      "InUnitsVanaf": null,
      "IndProjectObjectType": false,
      "IndTransactieMakelaarTonen": "true",
      "IsSearchable": true,
      "IsVerhuurd": false,
      "IsVerkocht": false,
      "IsVerkochtOfVerhuurd": false,
      "Koopprijs": 217000,
      "KoopprijsFormaat": "<[KoopPrijs]> <{kosten koper|kort}>",
      "KoopprijsTot": 217000,
      "MakelaarId": 12285,
      "MakelaarNaam": "Makelaarsland",
      "MobileURL": "http://m.funda.nl/obj.aspx?goi=2066858",
      "Note": null,
      "OpenHuis": [],
      "Oppervlakte": 0,
      "Perceeloppervlakte": null,
      "Postcode": "1094GL",
      "Prijs": {
        "GeenExtraKosten": null,
        "HuurAbbreviation": "",
        "Huurprijs": null,
        "HuurprijsOpAanvraag": "",
        "HuurprijsTot": null,
        "KoopAbbreviation": "k.k.",
        "Koopprijs": 217000,
        "KoopprijsOpAanvraag": "",
        "KoopprijsTot": 217000,
        "OriginelePrijs": null,
        "VeilingText": ""
      },
      "PrijsGeformatteerdHtml": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;217.000</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "PrijsGeformatteerdTextHuur": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;217.000</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "PrijsGeformatteerdTextKoop": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;217.000</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "Producten": [
        "Top",
        "Brochure"
      ],
      "ProjectNaam": null,
      "PromoLabel": {
        "HasPromotionLabel": false,
        "PromotionPhotos": [],
        "PromotionPhotosSecure": null,
        "PromotionType": 0,
        "RibbonColor": 0,
        "RibbonText": null,
        "Tagline": null
      },
      "PublicatieDatum": "2012-07-03T01:05:38+02:00",
      "PublicatieStatus": 0,
      "SavedDate": null,
      "Soort-aanbod": "appartement",
      "SoortAanbod": 10,
      "StartOplevering": null,
      "TimeAgoText": null,
      "TransactieAfmeldDatum": null,
      "TransactieMakelaarId": null,
      "TransactieMakelaarNaam": null,
      "TypeProject": 0,
      "URL": "http://www.funda.nl/koop/amsterdam/appartement-48411211-madurastraat-8-d/",
      "VerkoopStatus": "StatusBeschikbaar",
      "WGS84_X": 4.931987,
      "WGS84_Y": 52.36406,
      "WoonOppervlakteTot": 56,
      "Woonoppervlakte": 56,
      "Woonplaats": "Amsterdam",
      "ZoekType": [
        10
      ]
    },
    {
      "AangebodenSindsTekst": "10 mei 2014",
      "AanmeldDatum": "2010-01-01T00:00:00+01:00",
      "AantalKamers": 4,
      "AantalKavels": null,
      "Adres": "Arent Janszoon Ernststraat 751",
      "Afstand": 0,
      "BronCode": "NVM",
      "ChildrenObjects": [],
      "DatumOndertekeningAkte": null,
      "Foto": "http://cloud.funda.nl/valentina_media/044/388/084_klein.jpg",
      "FotoLarge": "http://cloud.funda.nl/valentina_media/044/388/084_groot.jpg",
      "FotoLargest": "http://cloud.funda.nl/valentina_media/044/388/084_grotere.jpg",
      "FotoMedium": "http://cloud.funda.nl/valentina_media/044/388/084_middel.jpg",
      "FotoSecure": "http://cloud.funda.nl/valentina_media/044/388/084_klein.jpg",
      "GewijzigdDatum": null,
      "GlobalId": 2662634,
      "GroupByObjectType": "a1c23983-4fa0-43b2-9ede-189b0e0b0826",
      "Heeft360GradenFoto": true,
      "HeeftBrochure": true,
      "HeeftOverbruggingsgrarantie": false,
      "HeeftPlattegrond": true,
      "HeeftTophuis": true,
      "HeeftVeiling": false,
      "HeeftVideo": true,
      "HuurPrijsTot": null,
      "Huurprijs": null,
      "HuurprijsFormaat": null,
      "Id": "a1c23983-4fa0-43b2-9ede-189b0e0b0826",
      "InUnitsVanaf": null,
      "IndProjectObjectType": false,
      "IndTransactieMakelaarTonen": "true",
      "IsSearchable": true,
      "IsVerhuurd": false,
      "IsVerkocht": false,
      "IsVerkochtOfVerhuurd": false,
      "Koopprijs": 259000,
      "KoopprijsFormaat": "<[KoopPrijs]> <{kosten koper|kort}>",
      "KoopprijsTot": 259000,
      "MakelaarId": 24761,
      "MakelaarNaam": "Francis Helmig Makelaardij",
      "MobileURL": "http://m.funda.nl/obj.aspx?goi=2662634",
      "Note": null,
      "OpenHuis": [],
      "Oppervlakte": 0,
      "Perceeloppervlakte": null,
      "Postcode": "1082LK",
      "Prijs": {
        "GeenExtraKosten": null,
        "HuurAbbreviation": "",
        "Huurprijs": null,
        "HuurprijsOpAanvraag": "",
        "HuurprijsTot": null,
        "KoopAbbreviation": "k.k.",
        "Koopprijs": 259000,
        "KoopprijsOpAanvraag": "",
        "KoopprijsTot": 259000,
        "OriginelePrijs": null,
        "VeilingText": ""
      },
      "PrijsGeformatteerdHtml": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;259.000</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "PrijsGeformatteerdTextHuur": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;259.000</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "PrijsGeformatteerdTextKoop": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;259.000</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "Producten": [
        "Top",
        "Video",
        "Plattegrond",
        "360-fotos",
        "Brochure"
      ],
      "ProjectNaam": null,
      "PromoLabel": {
        "HasPromotionLabel": false,
        "PromotionPhotos": [],
        "PromotionPhotosSecure": null,
        "PromotionType": 0,
        "RibbonColor": 0,
        "RibbonText": null,
        "Tagline": null
      },
      "PublicatieDatum": "2014-05-10T01:05:13+02:00",
      "PublicatieStatus": 0,
      "SavedDate": null,
      "Soort-aanbod": "appartement",
      "SoortAanbod": 10,
      "StartOplevering": null,
      "TimeAgoText": null,
      "TransactieAfmeldDatum": null,
      "TransactieMakelaarId": null,
      "TransactieMakelaarNaam": null,
      "TypeProject": 0,
      "URL": "http://www.funda.nl/koop/amsterdam/appartement-48017097-arent-janszoon-ernststraat-751/",
      "VerkoopStatus": "StatusBeschikbaar",
      "WGS84_X": 4.871333,
      "WGS84_Y": 52.3319,
      "WoonOppervlakteTot": 81,
      "Woonoppervlakte": 81,
      "Woonplaats": "Amsterdam",
      "ZoekType": [
        10
      ]
    },
    {
      "AangebodenSindsTekst": "15 mei 2014",
      "AanmeldDatum": "2010-01-01T00:00:00+01:00",
      "AantalKamers": 4,
      "AantalKavels": null,
      "Adres": "Amstelveenseweg 986 C",
      "Afstand": 0,
      "BronCode": "NVM",
      "ChildrenObjects": [],
      "DatumOndertekeningAkte": null,
      "Foto": "http://cloud.funda.nl/valentina_media/044/527/388_klein.jpg",
      "FotoLarge": "http://cloud.funda.nl/valentina_media/044/527/388_groot.jpg",
      "FotoLargest": "http://cloud.funda.nl/valentina_media/044/527/388_grotere.jpg",
      "FotoMedium": "http://cloud.funda.nl/valentina_media/044/527/388_middel.jpg",
      "FotoSecure": "http://cloud.funda.nl/valentina_media/044/527/388_klein.jpg",
      "GewijzigdDatum": null,
      "GlobalId": 2667385,
      "GroupByObjectType": "2dcaa927-1ec0-4f6e-b96d-b55c56de3426",
      "Heeft360GradenFoto": false,
      "HeeftBrochure": false,
      "HeeftOverbruggingsgrarantie": false,
      "HeeftPlattegrond": false,
      "HeeftTophuis": true,
      "HeeftVeiling": false,
      "HeeftVideo": false,
      "HuurPrijsTot": null,
      "Huurprijs": null,
      "HuurprijsFormaat": null,
      "Id": "2dcaa927-1ec0-4f6e-b96d-b55c56de3426",
      "InUnitsVanaf": null,
      "IndProjectObjectType": false,
      "IndTransactieMakelaarTonen": "true",
      "IsSearchable": true,
      "IsVerhuurd": false,
      "IsVerkocht": false,
      "IsVerkochtOfVerhuurd": false,
      "Koopprijs": 399500,
      "KoopprijsFormaat": "<[KoopPrijs]> <{kosten koper|kort}>",
      "KoopprijsTot": 399500,
      "MakelaarId": 24022,
      "MakelaarNaam": "Gerard W. Bakker Makelaars B.V.",
      "MobileURL": "http://m.funda.nl/obj.aspx?goi=2667385",
      "Note": null,
      "OpenHuis": [],
      "Oppervlakte": 0,
      "Perceeloppervlakte": null,
      "Postcode": "1081JR",
      "Prijs": {
        "GeenExtraKosten": null,
        "HuurAbbreviation": "",
        "Huurprijs": null,
        "HuurprijsOpAanvraag": "",
        "HuurprijsTot": null,
        "KoopAbbreviation": "k.k.",
        "Koopprijs": 399500,
        "KoopprijsOpAanvraag": "",
        "KoopprijsTot": 399500,
        "OriginelePrijs": null,
        "VeilingText": ""
      },
      "PrijsGeformatteerdHtml": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;399.500</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "PrijsGeformatteerdTextHuur": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;399.500</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "PrijsGeformatteerdTextKoop": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;399.500</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "Producten": [
        "Top"
      ],
      "ProjectNaam": null,
      "PromoLabel": {
        "HasPromotionLabel": false,
        "PromotionPhotos": [],
        "PromotionPhotosSecure": null,
        "PromotionType": 0,
        "RibbonColor": 0,
        "RibbonText": null,
        "Tagline": null
      },
      "PublicatieDatum": "2014-05-15T01:05:14+02:00",
      "PublicatieStatus": 0,
      "SavedDate": null,
      "Soort-aanbod": "appartement",
      "SoortAanbod": 10,
      "StartOplevering": null,
      "TimeAgoText": null,
      "TransactieAfmeldDatum": null,
      "TransactieMakelaarId": null,
      "TransactieMakelaarNaam": null,
      "TypeProject": 0,
      "URL": "http://www.funda.nl/koop/amsterdam/appartement-48012748-amstelveenseweg-986-c/",
      "VerkoopStatus": "StatusBeschikbaar",
      "WGS84_X": 4.857211,
      "WGS84_Y": 52.32537,
      "WoonOppervlakteTot": 103,
      "Woonoppervlakte": 103,
      "Woonplaats": "Amsterdam",
      "ZoekType": [
        10
      ]
    },
    {
      "AangebodenSindsTekst": "15 mei 2014",
      "AanmeldDatum": "2010-01-01T00:00:00+01:00",
      "AantalKamers": 2,
      "AantalKavels": null,
      "Adres": "Vrolikstraat 407 D",
      "Afstand": 0,
      "BronCode": "NVM",
      "ChildrenObjects": [],
      "DatumOndertekeningAkte": null,
      "Foto": "http://cloud.funda.nl/valentina_media/044/534/961_klein.jpg",
      "FotoLarge": "http://cloud.funda.nl/valentina_media/044/534/961_groot.jpg",
      "FotoLargest": "http://cloud.funda.nl/valentina_media/044/534/961_grotere.jpg",
      "FotoMedium": "http://cloud.funda.nl/valentina_media/044/534/961_middel.jpg",
      "FotoSecure": "http://cloud.funda.nl/valentina_media/044/534/961_klein.jpg",
      "GewijzigdDatum": null,
      "GlobalId": 2667632,
      "GroupByObjectType": "873873fe-8320-4dbc-9c9d-a4103695dfd6",
      "Heeft360GradenFoto": false,
      "HeeftBrochure": false,
      "HeeftOverbruggingsgrarantie": false,
      "HeeftPlattegrond": false,
      "HeeftTophuis": true,
      "HeeftVeiling": false,
      "HeeftVideo": false,
      "HuurPrijsTot": null,
      "Huurprijs": null,
      "HuurprijsFormaat": null,
      "Id": "873873fe-8320-4dbc-9c9d-a4103695dfd6",
      "InUnitsVanaf": null,
      "IndProjectObjectType": false,
      "IndTransactieMakelaarTonen": "true",
      "IsSearchable": true,
      "IsVerhuurd": false,
      "IsVerkocht": false,
      "IsVerkochtOfVerhuurd": false,
      "Koopprijs": 149000,
      "KoopprijsFormaat": "<[KoopPrijs]> <{kosten koper|kort}>",
      "KoopprijsTot": 149000,
      "MakelaarId": 24755,
      "MakelaarNaam": "Amsterdam @ Home Makelaars",
      "MobileURL": "http://m.funda.nl/obj.aspx?goi=2667632",
      "Note": null,
      "OpenHuis": [],
      "Oppervlakte": 0,
      "Perceeloppervlakte": null,
      "Postcode": "1092TE",
      "Prijs": {
        "GeenExtraKosten": null,
        "HuurAbbreviation": "",
        "Huurprijs": null,
        "HuurprijsOpAanvraag": "",
        "HuurprijsTot": null,
        "KoopAbbreviation": "k.k.",
        "Koopprijs": 149000,
        "KoopprijsOpAanvraag": "",
        "KoopprijsTot": 149000,
        "OriginelePrijs": null,
        "VeilingText": ""
      },
      "PrijsGeformatteerdHtml": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;149.000</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "PrijsGeformatteerdTextHuur": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;149.000</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "PrijsGeformatteerdTextKoop": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;149.000</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "Producten": [
        "Top"
      ],
      "ProjectNaam": null,
      "PromoLabel": {
        "HasPromotionLabel": false,
        "PromotionPhotos": [],
        "PromotionPhotosSecure": null,
        "PromotionType": 0,
        "RibbonColor": 0,
        "RibbonText": null,
        "Tagline": null
      },
      "PublicatieDatum": "2014-05-15T01:05:14+02:00",
      "PublicatieStatus": 0,
      "SavedDate": null,
      "Soort-aanbod": "appartement",
      "SoortAanbod": 10,
      "StartOplevering": null,
      "TimeAgoText": null,
      "TransactieAfmeldDatum": null,
      "TransactieMakelaarId": null,
      "TransactieMakelaarNaam": null,
      "TypeProject": 0,
      "URL": "http://www.funda.nl/koop/amsterdam/appartement-48012095-vrolikstraat-407-d/",
      "VerkoopStatus": "StatusBeschikbaar",
      "WGS84_X": 4.921668,
      "WGS84_Y": 52.35735,
      "WoonOppervlakteTot": 40,
      "Woonoppervlakte": 40,
      "Woonplaats": "Amsterdam",
      "ZoekType": [
        10
      ]
    },
    {
      "AangebodenSindsTekst": "13 mei 2014",
      "AanmeldDatum": "2010-01-01T00:00:00+01:00",
      "AantalKamers": 3,
      "AantalKavels": null,
      "Adres": "IJburglaan 803 + PP",
      "Afstand": 0,
      "BronCode": "NVM",
      "ChildrenObjects": [],
      "DatumOndertekeningAkte": null,
      "Foto": "http://cloud.funda.nl/valentina_media/044/440/614_klein.jpg",
      "FotoLarge": "http://cloud.funda.nl/valentina_media/044/440/614_groot.jpg",
      "FotoLargest": "http://cloud.funda.nl/valentina_media/044/440/614_grotere.jpg",
      "FotoMedium": "http://cloud.funda.nl/valentina_media/044/440/614_middel.jpg",
      "FotoSecure": "http://cloud.funda.nl/valentina_media/044/440/614_klein.jpg",
      "GewijzigdDatum": null,
      "GlobalId": 2664435,
      "GroupByObjectType": "2f189ea0-565e-4e95-9cf8-273a250ba35a",
      "Heeft360GradenFoto": false,
      "HeeftBrochure": true,
      "HeeftOverbruggingsgrarantie": false,
      "HeeftPlattegrond": false,
      "HeeftTophuis": true,
      "HeeftVeiling": false,
      "HeeftVideo": false,
      "HuurPrijsTot": null,
      "Huurprijs": null,
      "HuurprijsFormaat": null,
      "Id": "2f189ea0-565e-4e95-9cf8-273a250ba35a",
      "InUnitsVanaf": null,
      "IndProjectObjectType": false,
      "IndTransactieMakelaarTonen": "true",
      "IsSearchable": true,
      "IsVerhuurd": false,
      "IsVerkocht": false,
      "IsVerkochtOfVerhuurd": false,
      "Koopprijs": 289000,
      "KoopprijsFormaat": "<[KoopPrijs]> <{kosten koper|kort}>",
      "KoopprijsTot": 289000,
      "MakelaarId": 24358,
      "MakelaarNaam": "Voorma & Millenaar makelaars - taxateurs o.g.",
      "MobileURL": "http://m.funda.nl/obj.aspx?goi=2664435",
      "Note": null,
      "OpenHuis": [
        "2014-06-11T18:00:00+02:00"
      ],
      "Oppervlakte": 0,
      "Perceeloppervlakte": null,
      "Postcode": "1087CL",
      "Prijs": {
        "GeenExtraKosten": null,
        "HuurAbbreviation": "",
        "Huurprijs": null,
        "HuurprijsOpAanvraag": "",
        "HuurprijsTot": null,
        "KoopAbbreviation": "k.k.",
        "Koopprijs": 289000,
        "KoopprijsOpAanvraag": "",
        "KoopprijsTot": 289000,
        "OriginelePrijs": null,
        "VeilingText": ""
      },
      "PrijsGeformatteerdHtml": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;289.000</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "PrijsGeformatteerdTextHuur": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;289.000</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "PrijsGeformatteerdTextKoop": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;289.000</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "Producten": [
        "Top",
        "Brochure"
      ],
      "ProjectNaam": null,
      "PromoLabel": {
        "HasPromotionLabel": false,
        "PromotionPhotos": [],
        "PromotionPhotosSecure": null,
        "PromotionType": 0,
        "RibbonColor": 0,
        "RibbonText": null,
        "Tagline": null
      },
      "PublicatieDatum": "2014-05-13T01:05:13+02:00",
      "PublicatieStatus": 0,
      "SavedDate": null,
      "Soort-aanbod": "appartement",
      "SoortAanbod": 10,
      "StartOplevering": null,
      "TimeAgoText": null,
      "TransactieAfmeldDatum": null,
      "TransactieMakelaarId": null,
      "TransactieMakelaarNaam": null,
      "TypeProject": 0,
      "URL": "http://www.funda.nl/koop/amsterdam/appartement-48019898-ijburglaan-803-pp/",
      "VerkoopStatus": "StatusBeschikbaar",
      "WGS84_X": 4.992414,
      "WGS84_Y": 52.35706,
      "WoonOppervlakteTot": 115,
      "Woonoppervlakte": 115,
      "Woonplaats": "Amsterdam",
      "ZoekType": [
        10
      ]
    },
    {
      "AangebodenSindsTekst": "2 weken",
      "AanmeldDatum": "2010-01-01T00:00:00+01:00",
      "AantalKamers": 3,
      "AantalKavels": null,
      "Adres": "Maldenhof 334",
      "Afstand": 0,
      "BronCode": "NVM",
      "ChildrenObjects": [],
      "DatumOndertekeningAkte": null,
      "Foto": "http://cloud.funda.nl/valentina_media/044/228/534_klein.jpg",
      "FotoLarge": "http://cloud.funda.nl/valentina_media/044/228/534_groot.jpg",
      "FotoLargest": "http://cloud.funda.nl/valentina_media/044/228/534_grotere.jpg",
      "FotoMedium": "http://cloud.funda.nl/valentina_media/044/228/534_middel.jpg",
      "FotoSecure": "http://cloud.funda.nl/valentina_media/044/228/534_klein.jpg",
      "GewijzigdDatum": null,
      "GlobalId": 2657180,
      "GroupByObjectType": "f3f741bc-986e-4161-aa8b-849f31f8dd1b",
      "Heeft360GradenFoto": false,
      "HeeftBrochure": true,
      "HeeftOverbruggingsgrarantie": true,
      "HeeftPlattegrond": true,
      "HeeftTophuis": true,
      "HeeftVeiling": false,
      "HeeftVideo": false,
      "HuurPrijsTot": null,
      "Huurprijs": null,
      "HuurprijsFormaat": null,
      "Id": "f3f741bc-986e-4161-aa8b-849f31f8dd1b",
      "InUnitsVanaf": null,
      "IndProjectObjectType": false,
      "IndTransactieMakelaarTonen": "true",
      "IsSearchable": true,
      "IsVerhuurd": false,
      "IsVerkocht": false,
      "IsVerkochtOfVerhuurd": false,
      "Koopprijs": 147500,
      "KoopprijsFormaat": "<[KoopPrijs]> <{kosten koper|kort}>",
      "KoopprijsTot": 147500,
      "MakelaarId": 24079,
      "MakelaarNaam": "Van der Linden",
      "MobileURL": "http://m.funda.nl/obj.aspx?goi=2657180",
      "Note": null,
      "OpenHuis": [],
      "Oppervlakte": 0,
      "Perceeloppervlakte": null,
      "Postcode": "1106EZ",
      "Prijs": {
        "GeenExtraKosten": null,
        "HuurAbbreviation": "",
        "Huurprijs": null,
        "HuurprijsOpAanvraag": "",
        "HuurprijsTot": null,
        "KoopAbbreviation": "k.k.",
        "Koopprijs": 147500,
        "KoopprijsOpAanvraag": "",
        "KoopprijsTot": 147500,
        "OriginelePrijs": null,
        "VeilingText": ""
      },
      "PrijsGeformatteerdHtml": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;147.500</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "PrijsGeformatteerdTextHuur": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;147.500</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "PrijsGeformatteerdTextKoop": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;147.500</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "Producten": [
        "Top",
        "Overbruggingsgarantie",
        "Plattegrond",
        "Brochure",
        "Featured"
      ],
      "ProjectNaam": null,
      "PromoLabel": {
        "HasPromotionLabel": true,
        "PromotionPhotos": [],
        "PromotionPhotosSecure": null,
        "PromotionType": 2,
        "RibbonColor": 1,
        "RibbonText": "betaalbaar",
        "Tagline": "Maisonnette met zonnig terras."
      },
      "PublicatieDatum": "2014-05-05T00:00:00+02:00",
      "PublicatieStatus": 0,
      "SavedDate": null,
      "Soort-aanbod": "appartement",
      "SoortAanbod": 10,
      "StartOplevering": null,
      "TimeAgoText": null,
      "TransactieAfmeldDatum": null,
      "TransactieMakelaarId": null,
      "TransactieMakelaarNaam": null,
      "TypeProject": 0,
      "URL": "http://www.funda.nl/koop/amsterdam/appartement-48002543-maldenhof-334/",
      "VerkoopStatus": "StatusBeschikbaar",
      "WGS84_X": 4.967513,
      "WGS84_Y": 52.30288,
      "WoonOppervlakteTot": 93,
      "Woonoppervlakte": 93,
      "Woonplaats": "Amsterdam",
      "ZoekType": [
        10
      ]
    },
    {
      "AangebodenSindsTekst": "5 maanden",
      "AanmeldDatum": "2010-01-01T00:00:00+01:00",
      "AantalKamers": 2,
      "AantalKavels": null,
      "Adres": "Hogevecht 134",
      "Afstand": 0,
      "BronCode": "NVM",
      "ChildrenObjects": [],
      "DatumOndertekeningAkte": null,
      "Foto": "http://cloud.funda.nl/valentina_media/041/064/609_klein.jpg",
      "FotoLarge": "http://cloud.funda.nl/valentina_media/041/064/609_groot.jpg",
      "FotoLargest": "http://cloud.funda.nl/valentina_media/041/064/609_grotere.jpg",
      "FotoMedium": "http://cloud.funda.nl/valentina_media/041/064/609_middel.jpg",
      "FotoSecure": "http://cloud.funda.nl/valentina_media/041/064/609_klein.jpg",
      "GewijzigdDatum": null,
      "GlobalId": 2523809,
      "GroupByObjectType": "b18ab5c7-779a-444b-bc2b-83746e59006b",
      "Heeft360GradenFoto": false,
      "HeeftBrochure": true,
      "HeeftOverbruggingsgrarantie": true,
      "HeeftPlattegrond": true,
      "HeeftTophuis": true,
      "HeeftVeiling": false,
      "HeeftVideo": false,
      "HuurPrijsTot": null,
      "Huurprijs": null,
      "HuurprijsFormaat": null,
      "Id": "b18ab5c7-779a-444b-bc2b-83746e59006b",
      "InUnitsVanaf": null,
      "IndProjectObjectType": false,
      "IndTransactieMakelaarTonen": "true",
      "IsSearchable": true,
      "IsVerhuurd": false,
      "IsVerkocht": false,
      "IsVerkochtOfVerhuurd": false,
      "Koopprijs": 107500,
      "KoopprijsFormaat": "<[KoopPrijs]> <{kosten koper|kort}>",
      "KoopprijsTot": 107500,
      "MakelaarId": 24079,
      "MakelaarNaam": "Van der Linden",
      "MobileURL": "http://m.funda.nl/obj.aspx?goi=2523809",
      "Note": null,
      "OpenHuis": [],
      "Oppervlakte": 0,
      "Perceeloppervlakte": null,
      "Postcode": "1102HG",
      "Prijs": {
        "GeenExtraKosten": null,
        "HuurAbbreviation": "",
        "Huurprijs": null,
        "HuurprijsOpAanvraag": "",
        "HuurprijsTot": null,
        "KoopAbbreviation": "k.k.",
        "Koopprijs": 107500,
        "KoopprijsOpAanvraag": "",
        "KoopprijsTot": 107500,
        "OriginelePrijs": null,
        "VeilingText": ""
      },
      "PrijsGeformatteerdHtml": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;107.500</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "PrijsGeformatteerdTextHuur": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;107.500</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "PrijsGeformatteerdTextKoop": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;107.500</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "Producten": [
        "Top",
        "Overbruggingsgarantie",
        "Plattegrond",
        "Brochure",
        "Featured"
      ],
      "ProjectNaam": null,
      "PromoLabel": {
        "HasPromotionLabel": true,
        "PromotionPhotos": [],
        "PromotionPhotosSecure": null,
        "PromotionType": 2,
        "RibbonColor": 1,
        "RibbonText": "betaalbaar",
        "Tagline": "Appartement met balkon en berging."
      },
      "PublicatieDatum": "2013-12-08T00:00:00+01:00",
      "PublicatieStatus": 0,
      "SavedDate": null,
      "Soort-aanbod": "appartement",
      "SoortAanbod": 10,
      "StartOplevering": null,
      "TimeAgoText": null,
      "TransactieAfmeldDatum": null,
      "TransactieMakelaarId": null,
      "TransactieMakelaarNaam": null,
      "TypeProject": 0,
      "URL": "http://www.funda.nl/koop/amsterdam/appartement-48978262-hogevecht-134/",
      "VerkoopStatus": "StatusBeschikbaar",
      "WGS84_X": 4.956747,
      "WGS84_Y": 52.30946,
      "WoonOppervlakteTot": 64,
      "Woonoppervlakte": 64,
      "Woonplaats": "Amsterdam",
      "ZoekType": [
        10
      ]
    },
    {
      "AangebodenSindsTekst": "5 maanden",
      "AanmeldDatum": "2010-01-01T00:00:00+01:00",
      "AantalKamers": 2,
      "AantalKavels": null,
      "Adres": "Vianenstraat 162",
      "Afstand": 0,
      "BronCode": "NVM",
      "ChildrenObjects": [],
      "DatumOndertekeningAkte": null,
      "Foto": "http://cloud.funda.nl/valentina_media/040/663/050_klein.jpg",
      "FotoLarge": "http://cloud.funda.nl/valentina_media/040/663/050_groot.jpg",
      "FotoLargest": "http://cloud.funda.nl/valentina_media/040/663/050_grotere.jpg",
      "FotoMedium": "http://cloud.funda.nl/valentina_media/040/663/050_middel.jpg",
      "FotoSecure": "http://cloud.funda.nl/valentina_media/040/663/050_klein.jpg",
      "GewijzigdDatum": null,
      "GlobalId": 2513649,
      "GroupByObjectType": "d79eb405-6468-4d41-9b1e-b3ab95339efc",
      "Heeft360GradenFoto": false,
      "HeeftBrochure": true,
      "HeeftOverbruggingsgrarantie": true,
      "HeeftPlattegrond": true,
      "HeeftTophuis": true,
      "HeeftVeiling": false,
      "HeeftVideo": false,
      "HuurPrijsTot": null,
      "Huurprijs": null,
      "HuurprijsFormaat": null,
      "Id": "d79eb405-6468-4d41-9b1e-b3ab95339efc",
      "InUnitsVanaf": null,
      "IndProjectObjectType": false,
      "IndTransactieMakelaarTonen": "true",
      "IsSearchable": true,
      "IsVerhuurd": false,
      "IsVerkocht": false,
      "IsVerkochtOfVerhuurd": false,
      "Koopprijs": 105000,
      "KoopprijsFormaat": "<[KoopPrijs]> <{kosten koper|kort}>",
      "KoopprijsTot": 105000,
      "MakelaarId": 24079,
      "MakelaarNaam": "Van der Linden",
      "MobileURL": "http://m.funda.nl/obj.aspx?goi=2513649",
      "Note": null,
      "OpenHuis": [],
      "Oppervlakte": 0,
      "Perceeloppervlakte": null,
      "Postcode": "1106DE",
      "Prijs": {
        "GeenExtraKosten": null,
        "HuurAbbreviation": "",
        "Huurprijs": null,
        "HuurprijsOpAanvraag": "",
        "HuurprijsTot": null,
        "KoopAbbreviation": "k.k.",
        "Koopprijs": 105000,
        "KoopprijsOpAanvraag": "",
        "KoopprijsTot": 105000,
        "OriginelePrijs": null,
        "VeilingText": ""
      },
      "PrijsGeformatteerdHtml": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;105.000</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "PrijsGeformatteerdTextHuur": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;105.000</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "PrijsGeformatteerdTextKoop": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;105.000</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "Producten": [
        "Top",
        "Overbruggingsgarantie",
        "Plattegrond",
        "Brochure",
        "Featured"
      ],
      "ProjectNaam": null,
      "PromoLabel": {
        "HasPromotionLabel": true,
        "PromotionPhotos": [],
        "PromotionPhotosSecure": null,
        "PromotionType": 2,
        "RibbonColor": 1,
        "RibbonText": "betaalbaar",
        "Tagline": "Bovenwoning met balkon en berging."
      },
      "PublicatieDatum": "2013-11-28T00:00:00+01:00",
      "PublicatieStatus": 0,
      "SavedDate": null,
      "Soort-aanbod": "appartement",
      "SoortAanbod": 10,
      "StartOplevering": null,
      "TimeAgoText": null,
      "TransactieAfmeldDatum": null,
      "TransactieMakelaarId": null,
      "TransactieMakelaarNaam": null,
      "TypeProject": 0,
      "URL": "http://www.funda.nl/koop/amsterdam/appartement-48968002-vianenstraat-162/",
      "VerkoopStatus": "StatusBeschikbaar",
      "WGS84_X": 4.983946,
      "WGS84_Y": 52.29827,
      "WoonOppervlakteTot": 53,
      "Woonoppervlakte": 53,
      "Woonplaats": "Amsterdam",
      "ZoekType": [
        10
      ]
    },
    {
      "AangebodenSindsTekst": "5 maanden",
      "AanmeldDatum": "2010-01-01T00:00:00+01:00",
      "AantalKamers": 3,
      "AantalKavels": null,
      "Adres": "Leksmondhof 285",
      "Afstand": 0,
      "BronCode": "NVM",
      "ChildrenObjects": [],
      "DatumOndertekeningAkte": null,
      "Foto": "http://cloud.funda.nl/valentina_media/040/663/459_klein.jpg",
      "FotoLarge": "http://cloud.funda.nl/valentina_media/040/663/459_groot.jpg",
      "FotoLargest": "http://cloud.funda.nl/valentina_media/040/663/459_grotere.jpg",
      "FotoMedium": "http://cloud.funda.nl/valentina_media/040/663/459_middel.jpg",
      "FotoSecure": "http://cloud.funda.nl/valentina_media/040/663/459_klein.jpg",
      "GewijzigdDatum": null,
      "GlobalId": 2513663,
      "GroupByObjectType": "1b24902d-f6f1-4693-9dcb-e304028e14e4",
      "Heeft360GradenFoto": false,
      "HeeftBrochure": true,
      "HeeftOverbruggingsgrarantie": true,
      "HeeftPlattegrond": true,
      "HeeftTophuis": true,
      "HeeftVeiling": false,
      "HeeftVideo": false,
      "HuurPrijsTot": null,
      "Huurprijs": null,
      "HuurprijsFormaat": null,
      "Id": "1b24902d-f6f1-4693-9dcb-e304028e14e4",
      "InUnitsVanaf": null,
      "IndProjectObjectType": false,
      "IndTransactieMakelaarTonen": "true",
      "IsSearchable": true,
      "IsVerhuurd": false,
      "IsVerkocht": false,
      "IsVerkochtOfVerhuurd": false,
      "Koopprijs": 112500,
      "KoopprijsFormaat": "<[KoopPrijs]> <{kosten koper|kort}>",
      "KoopprijsTot": 112500,
      "MakelaarId": 24079,
      "MakelaarNaam": "Van der Linden",
      "MobileURL": "http://m.funda.nl/obj.aspx?goi=2513663",
      "Note": null,
      "OpenHuis": [],
      "Oppervlakte": 0,
      "Perceeloppervlakte": null,
      "Postcode": "1108GB",
      "Prijs": {
        "GeenExtraKosten": null,
        "HuurAbbreviation": "",
        "Huurprijs": null,
        "HuurprijsOpAanvraag": "",
        "HuurprijsTot": null,
        "KoopAbbreviation": "k.k.",
        "Koopprijs": 112500,
        "KoopprijsOpAanvraag": "",
        "KoopprijsTot": 112500,
        "OriginelePrijs": null,
        "VeilingText": ""
      },
      "PrijsGeformatteerdHtml": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;112.500</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "PrijsGeformatteerdTextHuur": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;112.500</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "PrijsGeformatteerdTextKoop": "<span class=\"price-wrapper\"><span class=\"price\">&euro;&nbsp;112.500</span> <abbr class=\"price-ext\">k.k.</abbr></span>",
      "Producten": [
        "Top",
        "Overbruggingsgarantie",
        "Plattegrond",
        "Brochure",
        "Featured"
      ],
      "ProjectNaam": null,
      "PromoLabel": {
        "HasPromotionLabel": true,
        "PromotionPhotos": [],
        "PromotionPhotosSecure": null,
        "PromotionType": 2,
        "RibbonColor": 1,
        "RibbonText": "betaalbaar",
        "Tagline": "Prachtig gelegen aan de Gaasperplas."
      },
      "PublicatieDatum": "2013-11-28T00:00:00+01:00",
      "PublicatieStatus": 0,
      "SavedDate": null,
      "Soort-aanbod": "appartement",
      "SoortAanbod": 10,
      "StartOplevering": null,
      "TimeAgoText": null,
      "TransactieAfmeldDatum": null,
      "TransactieMakelaarId": null,
      "TransactieMakelaarNaam": null,
      "TypeProject": 0,
      "URL": "http://www.funda.nl/koop/amsterdam/appartement-48968026-leksmondhof-285/",
      "VerkoopStatus": "StatusBeschikbaar",
      "WGS84_X": 4.981088,
      "WGS84_Y": 52.30942,
      "WoonOppervlakteTot": 65,
      "Woonoppervlakte": 65,
      "Woonplaats": "Amsterdam",
      "ZoekType": [
        10
      ]
    }
  ],
  "Paging": {
    "AantalPaginas": 518,
    "HuidigePagina": 1,
    "VolgendeUrl": "/~/koop/amsterdam/p2/",
    "VorigeUrl": null
  },
  "TotaalAantalObjecten": 7763
}